name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      # Create output_figures directory if it doesn't exist in the repo
      - name: Create directories
        run: |
          mkdir -p output_figures
          mkdir -p example_data

      # Copy files from repo if they exist
      - name: Copy visualization files
        run: |
          cp -r output_figures/* output_figures/ || true
          cp -r example_data/* example_data/ || true

      - name: Build static files
        run: |
          python build_static.py
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true