name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dash==2.12.1
          pip install dash-bootstrap-components==1.4.1
          pip install plotly==5.15.0
          pip install pandas==2.0.3
          pip install numpy==1.24.3
          pip install networkx==3.1
          pip install scikit-learn==1.3.0
          pip install hmmlearn==0.3.0

      # Create output_figures directory (GitHub Actions won't have these files)
      # We're creating empty files here just to make sure the build process works
      - name: Create placeholder visualization files
        run: |
          mkdir -p output_figures
          touch output_figures/interactive_market_regimes.html
          touch output_figures/interactive_network.html
          touch output_figures/interactive_pca_clustering.html
          touch output_figures/interactive_risk_metrics_comparison.html
          touch output_figures/interactive_risk_metrics_heatmap.html
          touch output_figures/pca_biplot.png
          touch output_figures/pca_clustering.png
          touch output_figures/regime_characteristics.png

      - name: Build static files
        run: |
          python build_static.py
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true